import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

const OUTPUT_PATH = resolve(process.cwd(), "src/generated/app-version.ts");
const FEAT_REGEX = /^feat(?:\([^)]*\))?!?:\s*/i;
const MARKER_REGEX = /^feat(?:\([^)]*\))?!?:\s*v(\d+)\b/i;

function readCommitSubjects() {
  if (process.env.GIT_COMMIT_SUBJECTS) {
    return process.env.GIT_COMMIT_SUBJECTS
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
  }

  try {
    const raw = execFileSync("git", ["log", "--format=%s"], {
      encoding: "utf8",
    });
    return raw
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);
  } catch (error) {
    console.warn("[generate-version] Unable to read git history:", error.message);
    return null;
  }
}

function computeVersion(subjects) {
  let major = 0;
  let minor = 0;
  let patch = 0;

  const markerIndex = subjects.findIndex((subject) => MARKER_REGEX.test(subject));
  if (markerIndex >= 0) {
    const match = subjects[markerIndex].match(MARKER_REGEX);
    major = Number(match?.[1] ?? 0);

    const afterMarker = subjects.slice(0, markerIndex);
    minor = afterMarker.filter((subject) => FEAT_REGEX.test(subject)).length;

    const latestFeatIndex = afterMarker.findIndex((subject) => FEAT_REGEX.test(subject));
    patch = latestFeatIndex >= 0 ? latestFeatIndex : afterMarker.length;
  } else {
    const latestFeatIndex = subjects.findIndex((subject) => FEAT_REGEX.test(subject));
    minor = subjects.filter((subject) => FEAT_REGEX.test(subject)).length;
    patch = latestFeatIndex >= 0 ? latestFeatIndex : subjects.length;
  }

  return `v${major}.${minor}.${patch}`;
}

function writeVersionFile(version) {
  const content = `// Auto-generated by scripts/generate-version.mjs\nexport const APP_VERSION = "${version}";\n`;

  let existing = "";
  try {
    existing = readFileSync(OUTPUT_PATH, "utf8");
  } catch {
    // Ignore missing file on first run.
  }

  if (existing === content) {
    console.log(`[generate-version] APP_VERSION unchanged (${version})`);
    return;
  }

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, content, "utf8");
  console.log(`[generate-version] APP_VERSION updated to ${version}`);
}

const subjects = readCommitSubjects();
if (subjects === null) {
  try {
    readFileSync(OUTPUT_PATH, "utf8");
    console.warn("[generate-version] Keeping existing version file.");
  } catch {
    writeVersionFile("v0.0.0");
  }
} else {
  const version = computeVersion(subjects);
  writeVersionFile(version);
}
